### ISSUE TITLE
Confirming licensing intent from contributors

### ISSUE THREAD

**Issue by kdavis-coqui** [erogol/TTS-papers#12]
Unfortunately we, while at Mozilla, forgot to add a license file to this repo when we created it.

As we were at Mozilla at the time we, and Mozilla, intended to use the default license for Mozilla projects, the Mozilla Public License 2.0. I'm tagging contributors to this repo asking you to confirm that you agree to license your contributions as MPL-2.0.

If you agree, please reply with a comment here saying "I agree to license my contributions to this repository under the Mozilla Public License 2.0."

- [x] @octalpixel
- [x] @shaun95

**Comment by SynthAether** [comment]
I agree to license my contributions to this repository under the Mozilla Public License 2.0.

**Comment by kdavis-coqui** [comment]
@octalpixel Ping!

**Comment by octalpixel** [comment]
Apologies, I missed this notification.

I agree to license my contributions to this repository under the Mozilla Public License 2.0.

**Comment by erogol** [comment]
Thx for the confirmation.
