### ISSUE TITLE
Is it possible to include some related materials

### ISSUE THREAD

**Issue by TonyWangX** [erogol/TTS-papers#17]
Hello Coqui team, 

Thank you for collecting many related works. 

I saw the tutorial "End-to-End Text-to-Speech Synthesis, Part 1 ". I am the presenter : ). 
That talk was quite old. The contents were based on my understanding by then and may be inaccurate or confusing.

Therefore, if it is possible, could I recommend some replacement? 
(the slides are on dropbox, and the link address may be too long to show here. Thus, I showed my github page link, from which it is easy to get the slides)

1. On neural vocoder, I and Prof. Yamagishi made a few tutorials on neural vocoders, and the latest one was here http://tonywangx.github.io/slide.html#may. The Pytorch-based hands-on materials cover a few presentative neural vocoders, and they are easy to run on the google colab platform. I think they may be useful to the newcomers;

2. On acoustic models, this tutorial given at ISCA Speaker Odyssey 2020 covered a few representative models. They may be old, but I think there is limited work covering both soft- and hard-attention-based approaches. They can be useful too: http://tonywangx.github.io/slide.html#label-slide-2020-nov-2.  The videos is here: https://youtu.be/WCe7SYcDzAI. 

Finally, Dr. Tan Xu's survey paper provides a comprehensive overview https://arxiv.org/abs/2106.15561.

Thank you!

**Comment by erogol** [comment]
Hey, thanks for the post here. Feel free to send a PR for this content
